### ISSUE TITLE
Provisioning fails due to undefined variable

### ISSUE THREAD

**Issue by Vlaszaty** [locationlabs/vagrant-packstack#1]
Hi,

When setting up the environment as described the provisioning fails with an undefined variable error. 

Vagrant 2.0.1, VBox 5.0.40_Ubuntur115130  ansible 2.3.1.0

============================================================
$ vagrant up
DEPRECATION: The 'sudo' option for the Ansible provisioner is deprecated.
Please use the 'become' option instead.
The 'sudo' option will be removed in a future release of Vagrant.

Bringing machine 'packstack' up with 'virtualbox' provider...
==> packstack: Importing base box 'bento/centos-7.3'...
==> packstack: Matching MAC address for NAT networking...
==> packstack: Checking if box 'bento/centos-7.3' is up to date...
==> packstack: Setting the name of the VM: vagrant-packstack_packstack_1513592329878_7437
==> packstack: Clearing any previously set network interfaces...
==> packstack: Preparing network interfaces based on configuration...
    packstack: Adapter 1: nat
    packstack: Adapter 2: hostonly
==> packstack: Forwarding ports...
    packstack: 22 (guest) => 2222 (host) (adapter 1)
==> packstack: Running 'pre-boot' VM customizations...
==> packstack: Booting VM...
==> packstack: Waiting for machine to boot. This may take a few minutes...
    packstack: SSH address: 127.0.0.1:2222
    packstack: SSH username: vagrant
    packstack: SSH auth method: private key
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
    packstack: Warning: Connection reset. Retrying...
    packstack: Warning: Remote connection disconnect. Retrying...
==> packstack: Machine booted and ready!
==> packstack: Checking for guest additions in VM...
    packstack: The guest additions on this VM do not match the installed version of
    packstack: VirtualBox! In most cases this is fine, but in rare cases it can
    packstack: prevent things such as shared folders from working properly. If you see
    packstack: shared folder errors, please make sure the guest additions within the
    packstack: virtual machine match the version of VirtualBox you have installed on
    packstack: your host and reload your VM.
    packstack: 
    packstack: Guest Additions Version: 5.1.26
    packstack: VirtualBox Version: 5.0
==> packstack: Setting hostname...
==> packstack: Configuring and enabling network interfaces...
    packstack: SSH address: 127.0.0.1:2222
    packstack: SSH username: vagrant
    packstack: SSH auth method: private key
==> packstack: Mounting shared folders...
    packstack: /vagrant => /home/vlaszaty/vms/vagrant-packstack
==> packstack: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> packstack: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
==> packstack: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.3.1.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    packstack: Running ansible-galaxy...
- el-network (1.0) is already installed, skipping.
    packstack: Running ansible-playbook...

PLAY [Upgrade the OS] **********************************************************

TASK [Gathering Facts] *********************************************************
ok: [packstack]

TASK [el-network : Disable NetworkManager] *************************************
changed: [packstack]

TASK [el-network : Discover list of interface config files] ********************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
ok: [packstack]

TASK [el-network : Add/Modify network interfaces] ******************************
changed: [packstack] => (item={u'gw4': u'10.0.2.2', u'iface': u'enp0s3', u'type': u'ethernet', u'ip4': u'10.0.2.15/24'})
changed: [packstack] => (item={u'iface': u'enp0s8', u'type': u'ethernet', u'ip4': u'172.16.0.10/24'})
changed: [packstack] => (item={u'iface': u'enp0s9', u'type': u'ethernet', u'ip4': u'172.16.1.10/24'})

TASK [el-network : Delete unconfigured network interfaces] *********************

TASK [Yum upgrade] *************************************************************
changed: [packstack]

RUNNING HANDLER [el-network : restart networking] ******************************
changed: [packstack]

TASK [Reboot host] *************************************************************
changed: [packstack]

TASK [Wait for the server to reboot] *******************************************
fatal: [packstack]: **FAILED**! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible_ssh_port' is undefined\n\nThe error appears to have been in '/home/vlaszaty/vms/vagrant-packstack/provisioning/vagrant/packstack-install.yml': line 23, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Wait for the server to reboot\n        ^ here\n"}

PLAY RECAP *********************************************************************
packstack                  : ok=10   changed=5    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by davidmnoriega** [comment]
I have changes staged that I need to push.

**Comment by davidmnoriega** [comment]
Give the develop branch a go

**Comment by Vlaszaty** [comment]
Tried develop branch, I still get undefined variable errors. It looks like something goes wrong with the el-network now. 

...........
==> packstack: Running provisioner: ansible...
    packstack: Running ansible-galaxy...
- downloading role 'el-network', owned by locationlabs
- downloading role from https://github.com/locationlabs/ansible-role_el-network/archive/1.0.tar.gz
- extracting el-network to /home/vlaszaty/vms/vagrant-packstack/provisioning/vagrant/shared-roles/el-network
- el-network (1.0) was installed successfully
    packstack: Running ansible-playbook...

PLAY [Upgrade the OS] **********************************************************

TASK [Gathering Facts] *********************************************************
ok: [packstack]

TASK [el-network : Disable NetworkManager] *************************************
changed: [packstack]

TASK [el-network : Discover list of interface config files] ********************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
ok: [packstack]

TASK [el-network : set_fact] ***************************************************
fatal: [packstack]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {{ el_network_interfaces | map(attribute='iface') | list }}: [{u'gw4': u'{{ ansible_default_ipv4.gateway }}', u'iface': u'enp0s3', u'type': u'ethernet', u'ip4': u'{{ ansible_default_ipv4.address }}/24'}, {u'iface': u'{{ local_interface }}', u'type': u'ethernet', u'ip4': u'{{ openstack_api_ip }}/24'}, {u'iface': u'{{ external_interface }}', u'type': u'ethernet', u'ip4': u'172.16.1.10/24'}]: {{ ansible_enp0s8.ipv4.address }}: 'dict object' has no attribute 'ipv4'\n\nThe error appears to have been in '/home/vlaszaty/vms/vagrant-packstack/provisioning/vagrant/shared-roles/el-network/tasks/discovery.yml': line 13, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

PLAY RECAP *********************************************************************
packstack                  : ok=5    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by Vlaszaty** [comment]
Did some investigating, found that on the vm the enp0s8 interface does not have an ipv4 address. This seems to be the issue...

**Comment by davidmnoriega** [comment]
@Vlaszaty Had some other changes on our end that hadn't found their way here, develop should be updated now.
